name: appwriter_repository
description: "The repo that uses appwriter"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter

    rxdart: ^0.28.0
    appwrite: ^16.0.0
    flutter_dotenv: ^5.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
